org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=rgp_client
mod_name=Rocket Game Platform Client
mod_license=All Rights Reserved
mod_version=2001.1.0
mod_group_id=net.rocketplatform.game
mod_authors=FTB Team
mod_description=Rocket Game Platform Client ported to 1.20.1